# Generated by Django 3.2.13 on 2022-05-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField()),
                ('Course', models.CharField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=30)),
            ],
        ),
    ]
