# Generated by Django 3.2.13 on 2022-05-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choiceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_name',
            new_name='name',
        ),
    ]
